In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/responses.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
5,5.0,3.0,2.0,3.0,2.0,3.0,3.0,2.0,5.0,5.0,...,20.0,186.0,77.0,1.0,male,right handed,secondary school,no,city,block of flats

In [3]:
df_adjusted = df.replace(2, 1)

In [4]:
df_adjusted = df_adjusted.replace(3, 2)

In [5]:
df_adjusted = df_adjusted.replace(4, 3)

In [6]:
df_adjusted = df_adjusted.replace(5, 3)

In [7]:
df_adjusted

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,3.0,...,19.0,163.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
2,3.0,3.0,1.0,1.0,2.0,3.0,3.0,2.0,3.0,2.0,...,20.0,176.0,67.0,1.0,female,right handed,secondary school,no,city,block of flats
4,3.0,2.0,3.0,2.0,1.0,3.0,2.0,3.0,2.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow
5,3.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,3.0,3.0,...,20.0,186.0,77.0,1.0,male,right handed,secondary school,no,city,block of flats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,3.0,2.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,...,22.0,175.0,60.0,1.0,male,right handed,secondary school,no,city,block of flats
1005,3.0,1.0,3.0,1.0,1.0,3.0,3.0,3.0,3.0,2.0,...,20.0,164.0,57.0,1.0,female,right handed,secondary school,no,city,house/bungalow
1007,3.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,...,18.0,173.0,75.0,0.0,female,right handed,secondary school,yes,city,block of flats
1008,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,3.0,1.0,...,25.0,173.0,58.0,1.0,female,right handed,college/bachelor degree,no,city,block of flats
1009,3.0,3.0,3.0,2.0,1.0,2.0,2.0,3.0,1.0,1.0,...,21.0,185.0,72.0,1.0,male,right handed,secondary school,no,village,house/bungalow

In [8]:
df_adjusted.to_csv('Data/responses_adjusted_scale_MOSHER.csv', index=False)